[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002BCD9BF57D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/96531bcb8653e271ba407be83ffdbd56
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002BCD9BF5F90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/96531bcb8653e271ba407be83ffdbd56
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002BCD9BF6850>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/96531bcb8653e271ba407be83ffdbd56