[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000281DAD40D10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/22ed72c3a120a3c779f5b38dba05a452
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000281DAD425D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/22ed72c3a120a3c779f5b38dba05a452
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000281DAD42DD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/22ed72c3a120a3c779f5b38dba05a452