[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000013DA47F8590>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/6b4ac9df635eecfdd72aacb8efa47b78
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000013DA47F89D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/6b4ac9df635eecfdd72aacb8efa47b78
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000013DA47F9110>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/6b4ac9df635eecfdd72aacb8efa47b78