[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023E09DB7B50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/16a77ffab141870581365da2f8fe35ae
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023E09DBC450>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/16a77ffab141870581365da2f8fe35ae
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023E09DBCC90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/16a77ffab141870581365da2f8fe35ae