[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B953875890>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e21308b52658f7ccfb06a063132eee8b
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B953876110>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e21308b52658f7ccfb06a063132eee8b
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B953876A10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/e21308b52658f7ccfb06a063132eee8b