[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CB81645F90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/52b658d2986b6ad84bc79c9854078d72
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CB81646810>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/52b658d2986b6ad84bc79c9854078d72
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CB81646F50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/52b658d2986b6ad84bc79c9854078d72