[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FDED55AD50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/3c270d24d0aedd305120fe82f81b749a
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FDED55B8D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/3c270d24d0aedd305120fe82f81b749a
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FDED564110>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/3c270d24d0aedd305120fe82f81b749a
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FDED8C7F10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/3c270d24d0aedd305120fe82f81b749a
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FDED8D4550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/3c270d24d0aedd305120fe82f81b749a
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FDED8D4DD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/3c270d24d0aedd305120fe82f81b749a