[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002122C646690>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c53877dad3ade961ed0a66472749a1e2
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002122C647150>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c53877dad3ade961ed0a66472749a1e2
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002122C647A50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c53877dad3ade961ed0a66472749a1e2