[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E0DE13E410>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/784db86e2d2626e1074fc7a8d41b4e95
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E0DE13EC10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/784db86e2d2626e1074fc7a8d41b4e95
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E0DE13F410>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/784db86e2d2626e1074fc7a8d41b4e95
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E0DE141590>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/784db86e2d2626e1074fc7a8d41b4e95
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E0DE141B50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/784db86e2d2626e1074fc7a8d41b4e95
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E0DE121AD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/784db86e2d2626e1074fc7a8d41b4e95