[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E0DE1313D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/598e1135f12c61e4ba4edf2cf0aed8fb
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E0DE130CD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/598e1135f12c61e4ba4edf2cf0aed8fb
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E0DE120D90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/598e1135f12c61e4ba4edf2cf0aed8fb