[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000185A58F5950>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/1b7408117f8a9b1610bed6155aaf3d2c
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000185A58F6250>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/1b7408117f8a9b1610bed6155aaf3d2c
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000185A58F69D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/1b7408117f8a9b1610bed6155aaf3d2c