[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000013E203B5C10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ba77e0c61223402986b337b28a7bcd71
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000013E203B6490>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ba77e0c61223402986b337b28a7bcd71
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000013E203B6C10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ba77e0c61223402986b337b28a7bcd71