[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020396F16450>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ad4f6202938531c56e096d60c7c939a6
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020396B95950>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ad4f6202938531c56e096d60c7c939a6
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020396F17650>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ad4f6202938531c56e096d60c7c939a6