[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B26F844390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/1808fd05005e82cb6f9eeecdbcd69eb2
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B26F844990>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/1808fd05005e82cb6f9eeecdbcd69eb2
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B26F8451D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/1808fd05005e82cb6f9eeecdbcd69eb2