[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023E09DCCF50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/3a319407e8a597692c7a09aa6973f8a0
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023E09DCD510>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/3a319407e8a597692c7a09aa6973f8a0
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023E09DCDC10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/3a319407e8a597692c7a09aa6973f8a0