[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000270EB922A90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/0d60cb682f661e05e852b7203795d010
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000270EB595050>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/0d60cb682f661e05e852b7203795d010
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000270EB935A50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/0d60cb682f661e05e852b7203795d010