[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000248E3C6DA10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/aec309fad56f042e2bc0534090e40756
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000248E3C6C250>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/aec309fad56f042e2bc0534090e40756
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000248E3C5F850>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/aec309fad56f042e2bc0534090e40756