[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F7C5FD0AD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/00c31ba43f26d87e598c40743eac2f3a
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F7C5FD1050>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/00c31ba43f26d87e598c40743eac2f3a
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F7C5FD1750>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/00c31ba43f26d87e598c40743eac2f3a