[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BE85A5250>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/191c7b9c1ccef3717886761564143dfe
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BE85A5A10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/191c7b9c1ccef3717886761564143dfe
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BE85A62D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/191c7b9c1ccef3717886761564143dfe