[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000248E3C57E90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f33850f2728e47fd5648a6238b6cc716
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000248E3C5C710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f33850f2728e47fd5648a6238b6cc716
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000248E3C5CF90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f33850f2728e47fd5648a6238b6cc716