[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020483AE2A10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/730a50d5752c1f7b0c88e642c3271894
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020483AE3210>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/730a50d5752c1f7b0c88e642c3271894
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020483AE3950>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/730a50d5752c1f7b0c88e642c3271894