[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000208313D4650>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7685e87e2762b21c4f318a2226060e08
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000208313E4950>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7685e87e2762b21c4f318a2226060e08
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000208313E5150>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7685e87e2762b21c4f318a2226060e08