[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C7DD765990>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/5743166dff547d020f537356c6410422
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C7DD766150>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/5743166dff547d020f537356c6410422
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C7DD766A90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/5743166dff547d020f537356c6410422