[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029DA6AD7D90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/31dddc0a16fdfc88bedee096f3776c80
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029DA6AD8850>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/31dddc0a16fdfc88bedee096f3776c80
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029DA6AD8F90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/31dddc0a16fdfc88bedee096f3776c80